// Generated by the Ballerina OpenAPI tool from specs/design/components/todo-api/openapi.yaml,
// then filled in: interceptable auth wiring and the three resource bodies.

import ballerina/constraint;
import ballerina/http;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    # The caller's todo items, oldest first
    #
    # + return - returns can be any of following types
    # TodoPage (A page of the caller's todo items)
    # ErrorUnauthorized (Not signed in)
    resource function get me/todos(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns TodoPage|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return <ErrorUnauthorized>{body: {code: 401, message: "not signed in"}};
        }
        int pageLimit = 'limit > 100 ? 100 : ('limit < 1 ? 1 : 'limit);
        int pageOffset = offset < 0 ? 0 : offset;
        return check storeListTodos(caller.userId, pageLimit, pageOffset);
    }

    # Add a new todo item for the caller
    #
    # + return - returns can be any of following types
    # Todo (The created todo item)
    # ErrorBadRequest (Missing or empty text)
    # ErrorUnauthorized (Not signed in)
    resource function post me/todos(http:RequestContext ctx, @http:Payload me_todos_body payload)
            returns Todo|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return <ErrorUnauthorized>{body: {code: 401, message: "not signed in"}};
        }
        string text = payload.text.trim();
        if text == "" {
            return <ErrorBadRequest>{body: {code: 400, message: "text is required"}};
        }
        return check storeCreateTodo(caller.userId, text);
    }

    # Mark one of the caller's todo items done
    #
    # + return - returns can be any of following types
    # TodoOk (The updated todo item)
    # ErrorNotFound (No such todo item for this caller)
    # ErrorUnauthorized (Not signed in)
    resource function post me/todos/[string todoId]/complete(http:RequestContext ctx)
            returns TodoOk|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return <ErrorUnauthorized>{body: {code: 401, message: "not signed in"}};
        }
        Todo? updated = check storeCompleteTodo(caller.userId, todoId);
        if updated is () {
            return <ErrorNotFound>{body: {code: 404, message: "no such todo"}};
        }
        return <TodoOk>{body: updated};
    }
}

public type TodoOk record {|
    *http:Ok;
    Todo body;
|};

public type Todo record {
    string id;
    string text;
    boolean done;
    string createdAt;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type TodoPage record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Todo[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type me_todos_body record {
    @constraint:String {maxLength: 500, minLength: 1}
    string text;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
